// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: internal/codec/message.proto

package codec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 中转消息
type TransitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitMessage) Reset() {
	*x = TransitMessage{}
	mi := &file_internal_codec_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitMessage) ProtoMessage() {}

func (x *TransitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitMessage.ProtoReflect.Descriptor instead.
func (*TransitMessage) Descriptor() ([]byte, []int) {
	return file_internal_codec_message_proto_rawDescGZIP(), []int{0}
}

func (x *TransitMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransitMessage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TransitMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// 接收消息
type ReceiveMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveMessage) Reset() {
	*x = ReceiveMessage{}
	mi := &file_internal_codec_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMessage) ProtoMessage() {}

func (x *ReceiveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_codec_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMessage.ProtoReflect.Descriptor instead.
func (*ReceiveMessage) Descriptor() ([]byte, []int) {
	return file_internal_codec_message_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiveMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ReceiveMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_internal_codec_message_proto protoreflect.FileDescriptor

const file_internal_codec_message_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/codec/message.proto\x12\x05codec\"V\n" +
	"\x0eTransitMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\">\n" +
	"\x0eReceiveMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessageB)Z'github.com/xfs0205/fernq/internal/codecb\x06proto3"

var (
	file_internal_codec_message_proto_rawDescOnce sync.Once
	file_internal_codec_message_proto_rawDescData []byte
)

func file_internal_codec_message_proto_rawDescGZIP() []byte {
	file_internal_codec_message_proto_rawDescOnce.Do(func() {
		file_internal_codec_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_codec_message_proto_rawDesc), len(file_internal_codec_message_proto_rawDesc)))
	})
	return file_internal_codec_message_proto_rawDescData
}

var file_internal_codec_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_codec_message_proto_goTypes = []any{
	(*TransitMessage)(nil), // 0: codec.TransitMessage
	(*ReceiveMessage)(nil), // 1: codec.ReceiveMessage
}
var file_internal_codec_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_codec_message_proto_init() }
func file_internal_codec_message_proto_init() {
	if File_internal_codec_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_codec_message_proto_rawDesc), len(file_internal_codec_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_codec_message_proto_goTypes,
		DependencyIndexes: file_internal_codec_message_proto_depIdxs,
		MessageInfos:      file_internal_codec_message_proto_msgTypes,
	}.Build()
	File_internal_codec_message_proto = out.File
	file_internal_codec_message_proto_goTypes = nil
	file_internal_codec_message_proto_depIdxs = nil
}
